# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0007_auto_20171119_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
